//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft
    {
        public Draft()
        {
            this.DraftPages = new HashSet<DraftPage>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int DraftId { get; set; }
        public int UserAccountId { get; set; }
        public int TemplateId { get; set; }
        public string DraftName { get; set; }
        public int DeliveryScheduleId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Template Template { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<DraftPage> DraftPages { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
