//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderAppliedPromoes = new HashSet<OrderAppliedPromo>();
            this.OrderItems = new HashSet<OrderItem>();
            this.PaymentInfoes = new HashSet<PaymentInfo>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int OrderId { get; set; }
        public int UserAccountId { get; set; }
        public string OrderReferance { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<OrderAppliedPromo> OrderAppliedPromoes { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
