//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCategoty
    {
        public TemplateCategoty()
        {
            this.Templates = new HashSet<Template>();
        }
    
        public int TemplateCategotyId { get; set; }
        public string TemplateCategotyCode { get; set; }
        public int StatusId { get; set; }
    
        public virtual ICollection<Template> Templates { get; set; }
    }
}
