//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public UserAddress()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.ShoppingCarts1 = new HashSet<ShoppingCart>();
        }
    
        public int UserAddressId { get; set; }
        public int UaserAccountId { get; set; }
        public int AddressTypeId { get; set; }
        public bool IsCurrentAddress { get; set; }
        public string SeconderyContact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string Country { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
