//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.Drafts = new HashSet<Draft>();
            this.Orders = new HashSet<Order>();
            this.OrderAppliedPromoes = new HashSet<OrderAppliedPromo>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public int UserAccountId { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public bool IsNewUser { get; set; }
        public bool IsAdmin { get; set; }
        public string PrimaryContact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string Country { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
        public string RowId { get; set; }
    
        public virtual ICollection<Draft> Drafts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrderAppliedPromo> OrderAppliedPromoes { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
