//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySchedule
    {
        public DeliverySchedule()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.TemplatePrices = new HashSet<TemplatePrice>();
        }
    
        public int DeliveryScheduleId { get; set; }
        public string DeliveryCode { get; set; }
        public int DeliveryFrom { get; set; }
        public int DeliveryTo { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<TemplatePrice> TemplatePrices { get; set; }
    }
}
