//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemPage
    {
        public int OrderItemPageId { get; set; }
        public int OrderItemId { get; set; }
        public int TemplateId { get; set; }
        public int TemplatePageId { get; set; }
        public string OrderPageUrl { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual Status Status { get; set; }
    }
}
