//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCode
    {
        public PromoCode()
        {
            this.OrderAppliedPromoes = new HashSet<OrderAppliedPromo>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int PromoCodeId { get; set; }
        public string PromoCodeName { get; set; }
        public decimal PromoAmount { get; set; }
        public int StatusId { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<OrderAppliedPromo> OrderAppliedPromoes { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
