//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int UserAccountId { get; set; }
        public int PaymentTypeId { get; set; }
        public int PaymentInfoId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> PromoCodeId { get; set; }
        public int BillingAddressId { get; set; }
        public int ShippingAddressId { get; set; }
        public string TransactionId { get; set; }
        public string CartReferance { get; set; }
        public System.DateTime ExpireOn { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentInfo PaymentInfo { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual PromoCode PromoCode { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAddress UserAddress { get; set; }
        public virtual UserAddress UserAddress1 { get; set; }
    }
}
