//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateType
    {
        public TemplateType()
        {
            this.Templates = new HashSet<Template>();
            this.TemplatePrices = new HashSet<TemplatePrice>();
        }
    
        public int TemplateTypeId { get; set; }
        public string TemplateCode { get; set; }
        public int StatusId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<TemplatePrice> TemplatePrices { get; set; }
    }
}
