//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePage
    {
        public TemplatePage()
        {
            this.DraftPages = new HashSet<DraftPage>();
        }
    
        public int TemplatePageId { get; set; }
        public int TemplateId { get; set; }
        public int PageHeight { get; set; }
        public int PageWidth { get; set; }
        public string TemplatePageUrl { get; set; }
        public string TemplatePageJson { get; set; }
        public int OrderIndex { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<DraftPage> DraftPages { get; set; }
        public virtual Status Status { get; set; }
        public virtual Template Template { get; set; }
    }
}
