//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keystone.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePrice
    {
        public int TemplatePriceId { get; set; }
        public int TemplateTypeId { get; set; }
        public int DeliveryScheduleId { get; set; }
        public string TemplatePriceCode { get; set; }
        public decimal TemplateHeight { get; set; }
        public decimal TemplateWidth { get; set; }
        public int PrintQuantity { get; set; }
        public decimal Price { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual DeliverySchedule DeliverySchedule { get; set; }
        public virtual Status Status { get; set; }
        public virtual TemplateType TemplateType { get; set; }
    }
}
